version: "3.8"
services:
  app:
    build:
      context: .  # Set the build context to the current directory
      dockerfile: Dockerfile  # Specify the path to your Dockerfile
    container_name: app-container
    ports:
      - '4000:4000'
    depends_on:
      - sql-server-db
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    expose:
      - "1433"
    ports:
      - "1433:1433"
    volumes:
      - backendDB:/data/db

volumes:
  backendDB:
